// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WSD_Project_CC2004V_Team08.Models;

namespace WSD_Project_CC2004V_Team08.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WSD_Project_CC2004V_Team08.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("password")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("WSD_Project_CC2004V_Team08.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("password")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WSD_Project_CC2004V_Team08.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("customer_ID");

                    b.Property<int?>("customersID");

                    b.Property<string>("delivery_address");

                    b.Property<DateTime>("delivery_date_time");

                    b.Property<string>("food_desc")
                        .IsRequired();

                    b.Property<DateTime>("order_date");

                    b.Property<int>("quantity");

                    b.HasKey("ID");

                    b.HasIndex("customersID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WSD_Project_CC2004V_Team08.Models.Order", b =>
                {
                    b.HasOne("WSD_Project_CC2004V_Team08.Models.Customer", "customers")
                        .WithMany()
                        .HasForeignKey("customersID");
                });
#pragma warning restore 612, 618
        }
    }
}
